// get all investments
export const REQUEST_INVESTMENTS = 'REQUEST_INVESTMENTS';
export const RECEIVE_INVESTMENTS = 'RECEIVE_INVESTMENTS';

// get connected investments
export const REQUEST_CONNECTED_INVESTMENTS = 'REQUEST_CONNECTED_INVESTMENTS';
export const RECEIVE_CONNECTED_INVESTMENTS = 'RECEIVE_CONNECTED_INVESTMENTS';

// get total numbers
export const REQUEST_TOTAL_NUMBERS = 'REQUEST_TOTAL_NUMBERS';
export const RECEIVE_TOTAL_NUMBERS = 'RECEIVE_TOTAL_NUMBERS';

// various trends filters
export const SET_TRENDS_FILTER = 'SET_TRENDS_FILTER';
export const SET_TRENDS_SECTION = 'SET_TRENDS_SECTION';

// get an investor
export const REQUEST_INVESTOR = 'REQUEST_INVESTOR';
export const RECEIVE_INVESTOR = 'RECEIVE_INVESTOR';

// get investor details
export const REQUEST_INVESTOR_DETAILS = 'REQUEST_INVESTOR_DETAILS';
export const RECEIVE_INVESTOR_DETAILS = 'RECEIVE_INVESTOR_DETAILS';

// get a company
export const REQUEST_COMPANY = 'REQUEST_COMPANY';
export const RECEIVE_COMPANY = 'RECEIVE_COMPANY';

// explore
export const SET_EXPLORE_FILTERS = 'SET_EXPLORE_FILTERS';
export const SET_EXPLORE_TABLE_SORT = 'SET_EXPLORE_TABLE_SORT';

// tabs
export const SET_INVESTOR_TAB = 'SET_INVESTOR_TAB';
export const SET_COMPANY_TAB = 'SET_COMPANY_TAB';

//search
export const SEARCH_REQUESTED = 'SEARCH_REQUESTED';
export const SEARCH_RECEIVED = 'SEARCH_RECEIVED';
